### ISSUE TITLE
OSError('Cannot detect %s device' % self.SENSE_HAT_FB_NAME)

### ISSUE THREAD

**Issue by theodorepsi** [astro-pi/python-sense-hat#112]
Hi there, I am trying to configure/connect to my Sense HAT (B) and when I try the following code:

from sense_hat import SenseHat
from datetime import datetime

sense = SenseHat()

def get_sense_data():
	sense_data = []

while True:
        print(get_sense_data())

I get the following error:

python3 SenseHatTest.py 
Traceback (most recent call last):
  File "SenseHatTest.py", line 4, in <module>
    sense = SenseHat()
  File "/usr/lib/python3/dist-packages/sense_hat/sense_hat.py", line 39, in __init__
    raise OSError('Cannot detect %s device' % self.SENSE_HAT_FB_NAME)
OSError: Cannot detect RPi-Sense FB device

I tried using the following commands as seen in a similar post and got the following output messages 

i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- 29 -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- 48 -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- 5c -- -- -- 
60: -- -- -- -- -- -- -- -- 68 -- -- -- -- -- -- -- 
70: 70 -- -- -- -- -- -- --                         

dmesg
[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 5.10.52+ (dom@buildbot) (arm-linux-gnueabihf-gcc-8 (Ubuntu/Linaro 8.4.0-3ubuntu1) 8.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #1441 Tue Aug 3 18:08:18 BST 2021
[    0.000000] CPU: ARMv6-compatible processor [410fb767] revision 7 (ARMv7), cr=00c5387d
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT nonaliasing instruction cache
[    0.000000] OF: fdt: Machine model: Raspberry Pi Zero W Rev 1.1
[    0.000000] random: fast init done
[    0.000000] Memory policy: Data cache writeback
[    0.000000] Reserved memory: created CMA memory pool at 0x17c00000, size 64 MiB
[    0.000000] OF: reserved mem: initialized node linux,cma, compatible id shared-dma-pool
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x0000000000000000-0x000000001bffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000000000-0x000000001bffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000000000-0x000000001bffffff]
[    0.000000] On node 0 totalpages: 114688
[    0.000000]   Normal zone: 1008 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 114688 pages, LIFO batch:31
[    0.000000] pcpu-alloc: s0 r0 d32768 u32768 alloc=1*32768
[    0.000000] pcpu-alloc: [0] 0 
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 113680
[    0.000000] Kernel command line: coherent_pool=1M 8250.nr_uarts=1 snd_bcm2835.enable_compat_alsa=0 snd_bcm2835.enable_hdmi=1 bcm2708_fb.fbwidth=656 bcm2708_fb.fbheight=416 bcm2708_fb.fbswap=1 smsc95xx.macaddr=B8:27:EB:57:EC:C7 vc_mem.mem_base=0x1ec00000 vc_mem.mem_size=0x20000000  console=ttyS0,115200 console=tty1 root=PARTUUID=09c3292b-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait modules-load=dwc2,g_ether
[    0.000000] Kernel parameter elevator= does not have any effect anymore.
               Please use sysfs to set IO scheduler for individual devices.
[    0.000000] Dentry cache hash table entries: 65536 (order: 6, 262144 bytes, linear)
[    0.000000] Inode-cache hash table entries: 32768 (order: 5, 131072 bytes, linear)
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory: 374400K/458752K available (8680K kernel code, 1324K rwdata, 2824K rodata, 424K init, 837K bss, 18816K reserved, 65536K cma-reserved)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] ftrace: allocating 30707 entries in 60 pages
[    0.000000] ftrace: allocated 60 pages with 4 groups
[    0.000000] NR_IRQS: 16, nr_irqs: 16, preallocated irqs: 16
[    0.000000] random: get_random_bytes called from start_kernel+0x324/0x560 with crng_init=1
[    0.000025] sched_clock: 32 bits at 1000kHz, resolution 1000ns, wraps every 2147483647500ns
[    0.000094] clocksource: timer: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 1911260446275 ns
[    0.000178] bcm2835: system timer (irq = 27)
[    0.000852] Console: colour dummy device 80x30
[    0.001540] printk: console [tty1] enabled
[    0.001636] Calibrating delay loop... 697.95 BogoMIPS (lpj=3489792)
[    0.060342] pid_max: default: 32768 minimum: 301
[    0.060642] LSM: Security Framework initializing
[    0.060970] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.061039] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.063069] cgroup: Disabling memory control group subsystem
[    0.063498] CPU: Testing write buffer coherency: ok
[    0.065316] Setting up static identity map for 0x8200 - 0x8238
[    0.066581] devtmpfs: initialized
[    0.079622] VFP support v0.3: implementor 41 architecture 1 part 20 variant b rev 5
[    0.080011] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.080093] futex hash table entries: 256 (order: -1, 3072 bytes, linear)
[    0.087889] pinctrl core: initialized pinctrl subsystem
[    0.089762] NET: Registered protocol family 16
[    0.094534] DMA: preallocated 1024 KiB pool for atomic coherent allocations
[    0.100955] audit: initializing netlink subsys (disabled)
[    0.102464] thermal_sys: Registered thermal governor 'step_wise'
[    0.103488] hw-breakpoint: found 6 breakpoint and 1 watchpoint registers.
[    0.103577] hw-breakpoint: maximum watchpoint size is 4 bytes.
[    0.103861] Serial: AMBA PL011 UART driver
[    0.110639] audit: type=2000 audit(0.100:1): state=initialized audit_enabled=0 res=1
[    0.129931] bcm2835-mbox 2000b880.mailbox: mailbox enabled
[    0.150798] raspberrypi-firmware soc:firmware: Attached to firmware from 2021-08-03T18:17:07, variant start
[    0.160814] raspberrypi-firmware soc:firmware: Firmware hash is 40787ee5905644f639a2a0f6e00ae12e517a2211
[    0.210886] Kprobes globally optimized
[    0.219727] bcm2835-dma 20007000.dma: DMA legacy API manager, dmachans=0x1
[    0.222878] SCSI subsystem initialized
[    0.223370] usbcore: registered new interface driver usbfs
[    0.223513] usbcore: registered new interface driver hub
[    0.223645] usbcore: registered new device driver usb
[    0.226401] clocksource: Switched to clocksource timer
[    2.230049] VFS: Disk quotas dquot_6.6.0
[    2.230231] VFS: Dquot-cache hash table entries: 1024 (order 0, 4096 bytes)
[    2.230531] FS-Cache: Loaded
[    2.230919] CacheFiles: Loaded
[    2.248929] NET: Registered protocol family 2
[    2.249275] IP idents hash table entries: 8192 (order: 4, 65536 bytes, linear)
[    2.250737] tcp_listen_portaddr_hash hash table entries: 512 (order: 0, 4096 bytes, linear)
[    2.250889] TCP established hash table entries: 4096 (order: 2, 16384 bytes, linear)
[    2.251015] TCP bind hash table entries: 4096 (order: 2, 16384 bytes, linear)
[    2.251143] TCP: Hash tables configured (established 4096 bind 4096)
[    2.251349] UDP hash table entries: 256 (order: 0, 4096 bytes, linear)
[    2.251429] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes, linear)
[    2.251902] NET: Registered protocol family 1
[    2.253183] RPC: Registered named UNIX socket transport module.
[    2.253253] RPC: Registered udp transport module.
[    2.253292] RPC: Registered tcp transport module.
[    2.253326] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    2.254891] hw perfevents: no irqs for PMU, sampling events not supported
[    2.255009] hw perfevents: enabled with armv6_1176 PMU driver, 3 counters available
[    2.259691] Initialise system trusted keyrings
[    2.260239] workingset: timestamp_bits=14 max_order=17 bucket_order=3
[    2.272460] zbud: loaded
[    2.275498] FS-Cache: Netfs 'nfs' registered for caching
[    2.277044] NFS: Registering the id_resolver key type
[    2.277168] Key type id_resolver registered
[    2.277210] Key type id_legacy registered
[    2.277458] nfs4filelayout_init: NFSv4 File Layout Driver Registering...
[    2.277514] nfs4flexfilelayout_init: NFSv4 Flexfile Layout Driver Registering...
[    2.279437] Key type asymmetric registered
[    2.279513] Asymmetric key parser 'x509' registered
[    2.279634] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 249)
[    2.279687] io scheduler mq-deadline registered
[    2.279724] io scheduler kyber registered
[    2.282976] bcm2708_fb soc:fb: FB found 1 display(s)
[    2.294503] Console: switching to colour frame buffer device 82x26
[    2.302158] bcm2708_fb soc:fb: Registered framebuffer for display 0, size 656x416
[    2.313380] Serial: 8250/16550 driver, 1 ports, IRQ sharing enabled
[    2.317782] bcm2835-aux-uart 20215040.serial: there is not valid maps for state default
[    2.326380] bcm2835-rng 20104000.rng: hwrng registered
[    2.330138] vc-mem: phys_addr:0x00000000 mem_base=0x1ec00000 mem_size:0x20000000(512 MiB)
[    2.337793] gpiomem-bcm2835 20200000.gpiomem: Initialised: Registers at 0x20200000
[    2.365440] brd: module loaded
[    2.384000] loop: module loaded
[    2.389569] Loading iSCSI transport class v2.0-870.
[    2.395187] libphy: Fixed MDIO Bus: probed
[    2.398860] usbcore: registered new interface driver smsc95xx
[    2.401985] dwc_otg: version 3.00a 10-AUG-2012 (platform bus)
[    2.405305] dwc_otg: FIQ enabled
[    2.405324] dwc_otg: NAK holdoff enabled
[    2.405338] dwc_otg: FIQ split-transaction FSM enabled
[    2.405363] Module dwc_common_port init
[    2.405833] usbcore: registered new interface driver usb-storage
[    2.409558] mousedev: PS/2 mouse device common for all mice
[    2.414460] bcm2835-wdt bcm2835-wdt: Broadcom BCM2835 watchdog timer
[    2.420701] sdhci: Secure Digital Host Controller Interface driver
[    2.423954] sdhci: Copyright(c) Pierre Ossman
[    2.427961] mmc-bcm2835 20300000.mmcnr: could not get clk, deferring probe
[    2.432155] sdhost-bcm2835 20202000.mmc: could not get clk, deferring probe
[    2.435671] sdhci-pltfm: SDHCI platform and OF driver helper
[    2.439698] ledtrig-cpu: registered to indicate activity on CPUs
[    2.443292] hid: raw HID events driver (C) Jiri Kosina
[    2.446680] usbcore: registered new interface driver usbhid
[    2.449622] usbhid: USB HID core driver
[    2.459671] Initializing XFRM netlink socket
[    2.462946] NET: Registered protocol family 17
[    2.466105] Key type dns_resolver registered
[    2.469897] registered taskstats version 1
[    2.472691] Loading compiled-in X.509 certificates
[    2.491991] uart-pl011 20201000.serial: cts_event_workaround enabled
[    2.495069] 20201000.serial: ttyAMA0 at MMIO 0x20201000 (irq = 81, base_baud = 0) is a PL011 rev2
[    2.503966] bcm2835-aux-uart 20215040.serial: there is not valid maps for state default
[    2.510894] printk: console [ttyS0] disabled
[    2.514054] 20215040.serial: ttyS0 at MMIO 0x20215040 (irq = 53, base_baud = 50000000) is a 16550
[    3.360722] printk: console [ttyS0] enabled
[    3.369610] bcm2835-power bcm2835-power: Broadcom BCM2835 power domains driver
[    3.382538] mmc-bcm2835 20300000.mmcnr: mmc_debug:0 mmc_debug2:0
[    3.391781] mmc-bcm2835 20300000.mmcnr: DMA channel allocated
[    3.429577] sdhost: log_buf @ (ptrval) (97d10000)
[    3.474146] mmc1: queuing unknown CIS tuple 0x80 (2 bytes)
[    3.484558] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    3.493132] mmc0: sdhost-bcm2835 loaded - DMA enabled (>1)
[    3.505850] of_cfs_init
[    3.531641] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    3.540457] of_cfs_init: OK
[    3.548934] Waiting for root device PARTUUID=09c3292b-02...
[    3.558572] mmc1: queuing unknown CIS tuple 0x80 (7 bytes)
[    3.602694] mmc0: host does not support reading read-only switch, assuming write-enable
[    3.619748] mmc0: new high speed SDHC card at address 59b4
[    3.630128] mmcblk0: mmc0:59b4 USDU1 14.9 GiB
[    3.641338]  mmcblk0: p1 p2
[    3.687719] EXT4-fs (mmcblk0p2): INFO: recovery required on readonly filesystem
[    3.698192] EXT4-fs (mmcblk0p2): write access will be enabled during recovery
[    3.739297] mmc1: new high speed SDIO card at address 0001
[    4.033223] EXT4-fs (mmcblk0p2): recovery complete
[    4.047298] EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Opts: (null)
[    4.061159] VFS: Mounted root (ext4 filesystem) readonly on device 179:2.
[    4.080764] devtmpfs: mounted
[    4.094211] Freeing unused kernel memory: 424K
[    4.101848] Kernel memory protection not selected by kernel config.
[    4.111363] Run /sbin/init as init process
[    4.118589]   with arguments:
[    4.118607]     /sbin/init
[    4.118619]   with environment:
[    4.118632]     HOME=/
[    4.118643]     TERM=linux
[    4.118655]     modules-load=dwc2,g_ether
[    4.868843] systemd[1]: System time before build time, advancing clock.
[    5.050747] NET: Registered protocol family 10
[    5.060640] Segment Routing with IPv6
[    5.156083] systemd[1]: systemd 241 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid)
[    5.189941] systemd[1]: Detected architecture arm.
[    5.229014] systemd[1]: Set hostname to <papaspi>.
[    7.780651] random: systemd: uninitialized urandom read (16 bytes read)
[    7.815978] random: systemd: uninitialized urandom read (16 bytes read)
[    7.827571] systemd[1]: Started Dispatch Password Requests to Console Directory Watch.
[    7.846791] random: systemd: uninitialized urandom read (16 bytes read)
[    7.858472] systemd[1]: Listening on Journal Socket (/dev/log).
[    7.873326] systemd[1]: Listening on Syslog Socket.
[    7.887549] systemd[1]: Listening on Journal Socket.
[    7.901453] systemd[1]: Condition check resulted in Huge Pages File System being skipped.
[    7.929563] systemd[1]: Mounting POSIX Message Queue File System...
[    7.977772] systemd[1]: Mounting RPC Pipe File System...
[    9.547774] dwc2 20980000.usb: supply vusb_d not found, using dummy regulator
[    9.587345] dwc2 20980000.usb: supply vusb_a not found, using dummy regulator
[    9.876704] dwc2 20980000.usb: EPs: 8, dedicated fifos, 4080 entries in SPRAM
[    9.947265] dwc2 20980000.usb: DWC OTG Controller
[    9.954889] dwc2 20980000.usb: new USB bus registered, assigned bus number 1
[   10.066851] dwc2 20980000.usb: irq 33, io mem 0x20980000
[   10.106920] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 5.10
[   10.120913] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[   10.131188] usb usb1: Product: DWC OTG Controller
[   10.138894] usb usb1: Manufacturer: Linux 5.10.52+ dwc2_hsotg
[   10.147589] usb usb1: SerialNumber: 20980000.usb
[   10.378295] systemd[1]: Started File System Check on Root Device.
[   10.407695] hub 1-0:1.0: USB hub found
[   10.427539] hub 1-0:1.0: 1 port detected
[   10.498533] systemd[1]: Starting Remount Root and Kernel File Systems...
[   10.720993] systemd[1]: Started Journal Service.
[   10.739138] using random self ethernet address
[   10.746765] using random host ethernet address
[   10.810546] usb0: HOST MAC c6:5f:0c:6c:7f:38
[   10.861167] usb0: MAC 32:d5:12:31:17:d4
[   10.896691] using random self ethernet address
[   10.904055] using random host ethernet address
[   10.963018] g_ether gadget: Ethernet Gadget, version: Memorial Day 2008
[   10.972657] g_ether gadget: g_ether ready
[   10.979316] dwc2 20980000.usb: bound driver g_ether
[   11.104743] i2c /dev entries driver
[   11.868409] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null)
[   12.457323] systemd-journald[97]: Received request to flush runtime journal from PID 1
[   16.720856] mc: Linux media interface: v0.10
[   16.959908] vc_sm_cma: module is from the staging directory, the quality is unknown, you have been warned.
[   16.962546] bcm2835_vc_sm_cma_probe: Videocore shared memory driver
[   16.962583] [vc_sm_connected_init]: start
[   16.995791] [vc_sm_connected_init]: installed successfully
[   17.165448] videodev: Linux video capture interface: v2.00
[   17.259166] bcm2835_mmal_vchiq: module is from the staging directory, the quality is unknown, you have been warned.
[   17.263675] bcm2835_mmal_vchiq: module is from the staging directory, the quality is unknown, you have been warned.
[   17.273730] bcm2835_isp: module is from the staging directory, the quality is unknown, you have been warned.
[   17.286656] bcm2835_v4l2: module is from the staging directory, the quality is unknown, you have been warned.
[   17.335361] bcm2835-isp bcm2835-isp: Device node output[0] registered as /dev/video13
[   17.337736] snd_bcm2835: module is from the staging directory, the quality is unknown, you have been warned.
[   17.340259] bcm2835_audio bcm2835_audio: there is not valid maps for state default
[   17.342275] bcm2835-isp bcm2835-isp: Device node capture[0] registered as /dev/video14
[   17.365256] bcm2835-isp bcm2835-isp: Device node capture[1] registered as /dev/video15
[   17.388169] bcm2835-isp bcm2835-isp: Device node stats[2] registered as /dev/video16
[   17.388226] bcm2835-isp bcm2835-isp: Register output node 0 with media controller
[   17.388273] bcm2835-isp bcm2835-isp: Register capture node 1 with media controller
[   17.388309] bcm2835-isp bcm2835-isp: Register capture node 2 with media controller
[   17.388343] bcm2835-isp bcm2835-isp: Register capture node 3 with media controller
[   17.392576] bcm2835-isp bcm2835-isp: Loaded V4L2 bcm2835-isp
[   17.427838] bcm2835_codec: module is from the staging directory, the quality is unknown, you have been warned.
[   17.472046] bcm2835-codec bcm2835-codec: Device registered as /dev/video10
[   17.472131] bcm2835-codec bcm2835-codec: Loaded V4L2 decode
[   17.510163] bcm2835-codec bcm2835-codec: Device registered as /dev/video11
[   17.510243] bcm2835-codec bcm2835-codec: Loaded V4L2 encode
[   17.547831] bcm2835-codec bcm2835-codec: Device registered as /dev/video12
[   17.547918] bcm2835-codec bcm2835-codec: Loaded V4L2 isp
[   19.871972] cfg80211: Loading compiled-in X.509 certificates for regulatory database
[   20.381106] cfg80211: Loaded X.509 cert 'sforshee: 00b28ddf47aef9cea7'
[   21.022255] brcmfmac: F1 signature read @0x18000000=0x1541a9a6
[   21.180398] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43430-sdio for chip BCM43430/1
[   21.195413] usbcore: registered new interface driver brcmfmac
[   21.472041] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43430-sdio for chip BCM43430/1
[   21.472287] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43430-sdio for chip BCM43430/1
[   21.472438] brcmfmac: brcmf_c_process_clm_blob: no clm_blob available (err=-2), device may have limited channels available
[   21.473642] brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM43430/1 wl0: Oct 22 2019 01:59:28 version 7.45.98.94 (r723000 CY) FWID 01-3b33decd
[   25.431731] random: crng init done
[   25.431767] random: 7 urandom warning(s) missed due to ratelimiting
[   26.572065] uart-pl011 20201000.serial: no DMA platform data
[   27.106220] Bluetooth: Core ver 2.22
[   27.106522] NET: Registered protocol family 31
[   27.106544] Bluetooth: HCI device and connection manager initialized
[   27.176608] Bluetooth: HCI socket layer initialized
[   27.176654] Bluetooth: L2CAP socket layer initialized
[   27.176730] Bluetooth: SCO socket layer initialized
[   27.211335] Bluetooth: HCI UART driver ver 2.3
[   27.211370] Bluetooth: HCI UART protocol H4 registered
[   27.211543] Bluetooth: HCI UART protocol Three-wire (H5) registered
[   27.211929] Bluetooth: HCI UART protocol Broadcom registered
[   27.279443] Adding 102396k swap on /var/swap.  Priority:-2 extents:1 across:102396k SSFS
[   28.923914] 8021q: 802.1Q VLAN Support v1.8
[   30.269611] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   30.269640] Bluetooth: BNEP filters: protocol multicast
[   30.269673] Bluetooth: BNEP socket layer initialized
[   31.049630] brcmfmac: brcmf_cfg80211_set_power_mgmt: power save enabled
[   33.408490] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready

---------------------------------------------------------------------------------------------------------

raspi-gpio get
BANK0 (GPIO 0 to 27):
GPIO 0: level=1 fsel=0 func=INPUT
GPIO 1: level=1 fsel=0 func=INPUT
GPIO 2: level=1 fsel=4 alt=0 func=SDA1
GPIO 3: level=1 fsel=4 alt=0 func=SCL1
GPIO 4: level=1 fsel=0 func=INPUT
GPIO 5: level=0 fsel=0 func=INPUT
GPIO 6: level=0 fsel=0 func=INPUT
GPIO 7: level=1 fsel=1 func=OUTPUT
GPIO 8: level=1 fsel=1 func=OUTPUT
GPIO 9: level=0 fsel=4 alt=0 func=SPI0_MISO
GPIO 10: level=0 fsel=4 alt=0 func=SPI0_MOSI
GPIO 11: level=0 fsel=4 alt=0 func=SPI0_SCLK
GPIO 12: level=0 fsel=0 func=INPUT
GPIO 13: level=0 fsel=0 func=INPUT
GPIO 14: level=1 fsel=2 alt=5 func=TXD1
GPIO 15: level=1 fsel=2 alt=5 func=RXD1
GPIO 16: level=0 fsel=0 func=INPUT
GPIO 17: level=0 fsel=0 func=INPUT
GPIO 18: level=0 fsel=0 func=INPUT
GPIO 19: level=0 fsel=0 func=INPUT
GPIO 20: level=0 fsel=0 func=INPUT
GPIO 21: level=0 fsel=0 func=INPUT
GPIO 22: level=0 fsel=0 func=INPUT
GPIO 23: level=0 fsel=0 func=INPUT
GPIO 24: level=0 fsel=0 func=INPUT
GPIO 25: level=0 fsel=0 func=INPUT
GPIO 26: level=0 fsel=0 func=INPUT
GPIO 27: level=0 fsel=0 func=INPUT
BANK1 (GPIO 28 to 45):
GPIO 28: level=1 fsel=0 func=INPUT
GPIO 29: level=1 fsel=0 func=INPUT
GPIO 30: level=0 fsel=7 alt=3 func=CTS0
GPIO 31: level=0 fsel=7 alt=3 func=RTS0
GPIO 32: level=1 fsel=7 alt=3 func=TXD0
GPIO 33: level=1 fsel=7 alt=3 func=RXD0
GPIO 34: level=0 fsel=7 alt=3 func=SD1_CLK
GPIO 35: level=1 fsel=7 alt=3 func=SD1_CMD
GPIO 36: level=1 fsel=7 alt=3 func=SD1_DAT0
GPIO 37: level=1 fsel=7 alt=3 func=SD1_DAT1
GPIO 38: level=1 fsel=7 alt=3 func=SD1_DAT2
GPIO 39: level=1 fsel=7 alt=3 func=SD1_DAT3
GPIO 40: level=1 fsel=1 func=OUTPUT
GPIO 41: level=1 fsel=1 func=OUTPUT
GPIO 42: level=0 fsel=0 func=INPUT
GPIO 43: level=1 fsel=4 alt=0 func=GPCLK2
GPIO 44: level=0 fsel=1 func=OUTPUT
GPIO 45: level=1 fsel=1 func=OUTPUT
BANK2 (GPIO 46 to 53):
GPIO 46: level=1 fsel=0 func=INPUT
GPIO 47: level=0 fsel=1 func=OUTPUT
GPIO 48: level=0 fsel=4 alt=0 func=SD0_CLK
GPIO 49: level=1 fsel=4 alt=0 func=SD0_CMD
GPIO 50: level=1 fsel=4 alt=0 func=SD0_DAT0
GPIO 51: level=1 fsel=4 alt=0 func=SD0_DAT1
GPIO 52: level=1 fsel=4 alt=0 func=SD0_DAT2
GPIO 53: level=1 fsel=4 alt=0 func=SD0_DAT3

Does anyone know why I get this error and how I can fix it? I'm wondering whether it is a faulty sense hat.

**Comment by richburdon** [comment]
I get the same error
