### ISSUE TITLE
Sense hat emulator error.

### ISSUE THREAD

**Issue by steveiliop56** [astro-pi/python-sense-hat#137]
When I try to run sense hat emulator it does not start up at all and it gives me this output:

 ```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sense_emu/gui.py", line 161, in do_startup
    self.imu = IMUServer(simulate_world=self.settings.get_boolean('simulate-imu'))
  File "/usr/lib/python3/dist-packages/sense_emu/imu.py", line 148, in __init__
    self._gyros = np.full((10, 3), self._gyro, dtype=np.float)
  File "/usr/local/lib/python3.9/dist-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sense_emu/gui.py", line 199, in do_activate
    self.window = MainWindow(application=self)
  File "/usr/lib/python3/dist-packages/sense_emu/gui.py", line 524, in __init__
    self.screen_widget = ScreenWidget(visible=True, client=self.props.application.screen)
AttributeError: 'EmuApplication' object has no  attribute 'screen'
```

**Comment by steveiliop56** [comment]
Fixed in https://github.com/astro-pi/python-sense-emu/pull/36.
